name: Test WIF with GCP

on:
  workflow_dispatch: {}

jobs:
  auth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # required for OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP using WIF
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Verify Identity
        run: |
          gcloud config set project $GCP_PROJECT
          gcloud auth list
          gcloud storage buckets list --limit 5
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
